GET http://localhost:5072/api/storage

###

POST http://localhost:5072/api/storage
Content-Type: application/json

{
    "Description": "Büro"
}

###
POST http://localhost:5072/api/storage
Content-Type: application/json

{
    "Description": "KellEr"
}

###

PATCH http://localhost:5072/api/storage
Content-Type: application/json

{
    "Id": "3081f97e-9ae2-4731-8fff-b3d2a6e95746",
    "Description": "Keller"
}