GET http://localhost:5072/api/storage

###

POST http://localhost:5072/api/storage
Content-Type: application/json

{
    "Description": "Büro"
}

###
POST http://localhost:5072/api/storage
Content-Type: application/json

{
    "Description": "KellEr"
}

###

PATCH http://localhost:5072/api/storage
Content-Type: application/json

{
    "Id": "c0682637-af60-41e9-b06e-8f968ec515b2",
    "Description": "Keller"
}

###

GET http://localhost:5072/api/storage/3b7ef21c-974b-403d-8154-f98b758388df

###
DELETE http://localhost:5072/api/storage/c0682637-af60-41e9-b06e-8f968ec515b2